version: 2
jobs:
    build:
        docker:
            - image: continuumio/miniconda3
        environment:
            TEST_OUTPUT: ~/artifacts
        steps:
            - checkout
            - run: conda install conda-build conda-verify codecov black
            - run: |
                mkdir -p ${TEST_OUTPUT}
                conda build .
            - run:
                name: Checking if 'black' needs to be run
                command: black --check .
                when: always
            - run: 
                name: Upload codecov
                command: |
                    find ${TEST_OUTPUT}
                    cat ${TEST_OUTPUT}/cov/coverage.xml
                    codecov -f ${TEST_OUTPUT}/cov/coverage.xml
                when: always
            - store_artifacts:
                path: ~/artifacts
            - store_test_results:
                path: ~/artifacts/pytest
